name: VioEnchants
version: 1.2
main: com.violentuso.vioEnchants.VioEnchants
api-version: 1.16
depends: WorldGuard
commands:
  vioenchant:
    description: Главная команда плагина
    usage: /vioenchant <give|enchant>